# Bài 01: Khám Phá Và Làm Quen Với Dữ Liệu (Chipotle)
### Giới thiệu:
Trong bài tập này, chúng ta sẽ làm quen với tập dữ liệu đơn hàng của chuỗi nhà hàng Chipotle. Bài tập giúp rèn luyện các kỹ năng đọc dữ liệu từ tệp TSV trên Internet, kiểm tra kích thước, thuộc tính, tính toán các thống kê mô tả cơ bản và làm sạch kiểu dữ liệu chuỗi thành số thực.

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2 & 3. Đọc dữ liệu từ URL và gán vào biến chipo
*Lưu ý: Tệp có định dạng .tsv (Tab-Separated Values) nên cần chỉ định phân cách bằng phím Tab sep='\t'.*

In [2]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. Xem 10 dòng đầu tiên của tập dữ liệu

In [3]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. Số lượng quan sát (hàng) trong tập dữ liệu là bao nhiêu?

In [4]:
print('Số quan sát (dòng):', chipo.shape[0])
# Cách khác: len(chipo)

Số quan sát (dòng): 4622

### Step 6. Số lượng cột trong tập dữ liệu là bao nhiêu?

In [5]:
print('Số cột:', chipo.shape[1])

Số cột: 5

### Step 7. In ra tên của tất cả các cột

In [6]:
print('Danh sách các cột:', list(chipo.columns))

Danh sách các cột: ['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. Tập dữ liệu được đánh chỉ số (index) như thế nào?

In [7]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Món ăn nào được đặt nhiều nhất?

In [8]:
most_ordered = chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False)
print('Món được đặt nhiều nhất:', most_ordered.index[0])

Món được đặt nhiều nhất: Chicken Bowl

### Step 10. Với món ăn được đặt nhiều nhất đó, tổng số lượng đã đặt là bao nhiêu?

In [9]:
print('Tổng số lượng của món đó:', most_ordered.iloc[0])

Tổng số lượng của món đó: 761

### Step 11. Món/phần mô tả kèm theo (choice_description) nào được đặt nhiều nhất?

In [10]:
most_choice = chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False)
print('Phần kèm theo được đặt nhiều nhất:', most_choice.index[0])
print('Số lượng:', most_choice.iloc[0])

Phần kèm theo được đặt nhiều nhất: [Diet Coke]
Số lượng: 159

### Step 12. Tổng số lượng tất cả các món đã được đặt là bao nhiêu?

In [11]:
total_items_ordered = chipo['quantity'].sum()
print('Tổng số lượng món đã đặt:', total_items_ordered)

Tổng số lượng món đã đặt: 4972

### Step 13. Chuyển đổi cột giá tiền (item_price) thành kiểu số thực (float)
#### Step 13.a. Kiểm tra kiểu dữ liệu ban đầu của cột item_price

In [12]:
print('Kiểu dữ liệu ban đầu của item_price:', chipo['item_price'].dtype)
chipo['item_price'].head()

Kiểu dữ liệu ban đầu của item_price: str

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: str

#### Step 13.b. Tạo hàm lambda và thay đổi kiểu dữ liệu của item_price

In [13]:
# Loại bỏ ký tự '$' và chuyển đổi sang float
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x.strip().replace('$', '')))
chipo['item_price'].head()

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: item_price, dtype: float64

#### Step 13.c. Kiểm tra lại kiểu dữ liệu của item_price sau khi chuyển đổi

In [14]:
print('Kiểu dữ liệu sau chuyển đổi:', chipo['item_price'].dtype)

Kiểu dữ liệu sau chuyển đổi: float64

### Step 14. Tổng doanh thu trong toàn bộ thời gian của tập dữ liệu là bao nhiêu?

In [15]:
# Doanh thu = tổng (số lượng * đơn giá)
# Lưu ý: trong dữ liệu Chipotle, item_price chính là tổng giá của dòng đó (item_price = quantity * unit_price).
# Nếu tính tổng doanh thu trực tiếp từ item_price:
revenue = chipo['item_price'].sum()
print(f'Tổng doanh thu: ')

Tổng doanh thu:

### Step 15. Có bao nhiêu đơn hàng (orders) đã được thực hiện?

In [16]:
num_orders = chipo['order_id'].nunique()
print('Số lượng đơn hàng duy nhất:', num_orders)

Số lượng đơn hàng duy nhất: 1834

### Step 16. Doanh thu trung bình trên mỗi đơn hàng là bao nhiêu?

In [17]:
avg_revenue_per_order = chipo.groupby('order_id')['item_price'].sum().mean()
print(f'Doanh thu trung bình trên mỗi đơn hàng: ')

Doanh thu trung bình trên mỗi đơn hàng:

### Step 17. Có bao nhiêu món ăn khác nhau (khác biệt) được bán?

In [18]:
num_different_items = chipo['item_name'].nunique()
print('Số lượng món ăn khác nhau:', num_different_items)

Số lượng món ăn khác nhau: 50