# Bài 06: Ghép Nối Dữ Liệu - Concat & Merge (Thị Trường Nhà Đất)
### Giới thiệu:
Trong bài tập này, chúng ta sẽ tự tạo dữ liệu mô phỏng thị trường bất động sản bằng thư viện NumPy và tìm hiểu cách ghép nối dữ liệu trong Pandas:
- Khởi tạo mảng số ngẫu nhiên với 
p.random.randint().
- Ghép nối dữ liệu theo chiều ngang (ghép cột - xis=1) bằng pd.concat().
- Đổi tên các cột của DataFrame.
- Ghép nối dữ liệu theo chiều dọc (ghép hàng - xis=0).
- Hiểu hiện tượng trùng lặp chỉ số (Duplicate Index) khi nối dọc và cách khắc phục bằng .reset_index().

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2. Tạo 3 Series khác nhau, mỗi Series có độ dài 100:
1. Series thứ nhất: số nguyên ngẫu nhiên từ 1 đến 4 (số phòng ngủ - bedrs)
2. Series thứ hai: số nguyên ngẫu nhiên từ 1 đến 3 (số phòng tắm - bathrs)
3. Series thứ ba: số nguyên ngẫu nhiên từ 10,000 đến 30,000 (giá tiền mỗi m2 - price_sqr_meter)

In [2]:
# Thiết lập seed để kết quả có thể tái lập
np.random.seed(42)

s1 = pd.Series(np.random.randint(1, 5, size=100))
s2 = pd.Series(np.random.randint(1, 4, size=100))
s3 = pd.Series(np.random.randint(10000, 30001, size=100))

print('Độ dài của s1, s2, s3:', len(s1), len(s2), len(s3))
s1.head()

Độ dài của s1, s2, s3: 100 100 100

0    3
1    4
2    1
3    3
4    3
dtype: int32

### Step 3. Tạo một DataFrame bằng cách ghép nối 3 Series theo cột (axis=1)

In [3]:
house = pd.concat([s1, s2, s3], axis=1)
house.head()

   0  1      2
0  3  3  23931
1  4  2  13627
2  1  2  26157
3  3  2  20173
4  3  2  28047

### Step 4. Đổi tên các cột thành: bedrs, bathrs, price_sqr_meter

In [4]:
house.columns = ['bedrs', 'bathrs', 'price_sqr_meter']
house.head()

   bedrs  bathrs  price_sqr_meter
0      3       3            23931
1      4       2            13627
2      1       2            26157
3      3       2            20173
4      3       2            28047

### Step 5. Tạo DataFrame 1 cột chứa toàn bộ giá trị của 3 Series ghép theo chiều dọc và gán vào biến 'bigcolumn' (axis=0)

In [5]:
bigcolumn = pd.concat([s1, s2, s3], axis=0).to_frame(name='bigcolumn')
bigcolumn

    bigcolumn
0           3
1           4
2           1
3           3
4           3
..        ...
95      11154
96      14499
97      16295
98      22183
99      22874

[300 rows x 1 columns]

### Step 6. Kiểm tra xem có đúng là chỉ số index chỉ chạy đến 99 hay không?
**Giải thích:** Đúng! Mặc dù DataFrame có 300 dòng (3 x 100), nhưng do mỗi Series gốc có index từ 0 đến 99, khi ghép nối dọc (axis=0) mặc định Pandas giữ nguyên index cũ. Do đó, các chỉ số từ 0 đến 99 bị lặp lại 3 lần!

In [6]:
print('Số lượng dòng:', len(bigcolumn))
print('Giá trị index lớn nhất:', bigcolumn.index.max())
print('Đoạn chỉ số xung quanh vị trí chuyển tiếp (dòng 98 đến 102):')
print(bigcolumn.iloc[98:103])

Số lượng dòng: 300
Giá trị index lớn nhất: 99
Đoạn chỉ số xung quanh vị trí chuyển tiếp (dòng 98 đến 102):
    bigcolumn
98          2
99          1
0           3
1           2
2           2

### Step 7. Đánh lại chỉ số (Reindex) DataFrame để chỉ số chạy liên tục từ 0 đến 299
*Sử dụng .reset_index(drop=True, inplace=True) để bỏ qua index cũ và tạo dải index mới.*

In [7]:
bigcolumn.reset_index(drop=True, inplace=True)
print('Giá trị index sau khi reset:', bigcolumn.index)
print('Dòng đầu và dòng cuối:')
print(bigcolumn.iloc[[0, 99, 100, 299]])

Giá trị index sau khi reset: RangeIndex(start=0, stop=300, step=1)
Dòng đầu và dòng cuối:
     bigcolumn
0            3
99           1
100          3
299      22874