# Bài 08: Xóa Và Xử Lý Dữ Liệu Thiếu - Deleting & Missing Values (Hoa Iris)
### Giới thiệu:
Tập dữ liệu hoa Iris (Iris Dataset) của nhà sinh vật học Ronald Fisher là một trong những tập dữ liệu kinh điển nhất trong Khoa học Dữ liệu. Bài tập này mô phỏng các tình huống thực tế của quy trình làm sạch dữ liệu (Data Cleaning):
- Đọc dữ liệu thô không có dòng tiêu đề (header=None) và tự định nghĩa tên cột.
- Phát hiện và kiểm tra dữ liệu bị thiếu (isnull() / isna()).
- Cố tình gán giá trị rỗng (
p.nan) vào các vùng dữ liệu cụ thể bằng .iloc.
- Điền khuyết dữ liệu (Imputation) bằng phương thức .fillna().
- Xóa bỏ một cột phân loại bằng del hoặc .drop().
- Loại bỏ các dòng chứa giá trị rỗng bằng .dropna().
- Tái lập chỉ số hàng bằng .reset_index(drop=True).

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2 & 3. Đọc dữ liệu từ URL và gán vào biến iris
*Lưu ý: Tệp iris.data không có dòng tiêu đề cột, do đó cần chỉ định header=None.*

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None)
iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

### Step 4. Đặt tên cột cho tập dữ liệu: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [3]:
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Step 5. Kiểm tra xem có giá trị thiếu (missing values) nào trong DataFrame không?

In [4]:
missing_counts = iris.isnull().sum()
print('Số lượng giá trị thiếu ở mỗi cột:')
print(missing_counts)

Số lượng giá trị thiếu ở mỗi cột:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6. Gán các giá trị từ dòng 10 đến 29 của cột 'petal_length' thành NaN
*Sử dụng .iloc[10:30, 2] = np.nan (vị trí dòng 10 đến 29 và cột thứ 3 index 2).*

In [5]:
iris.iloc[10:30, 2] = np.nan
print('Kiểm tra giá trị thiếu ở dòng 10 đến 14:')
print(iris.loc[10:14, ['sepal_length', 'petal_length']])

Kiểm tra giá trị thiếu ở dòng 10 đến 14:
    sepal_length  petal_length
10           5.4           NaN
11           4.8           NaN
12           4.8           NaN
13           4.3           NaN
14           5.8           NaN

### Step 7. Thay thế (điền) các giá trị NaN vừa tạo bằng số 1.0

In [6]:
iris['petal_length'] = iris['petal_length'].fillna(1.0)
print('Kiểm tra lại dòng 10 đến 14 sau khi điền 1.0:')
print(iris.loc[10:14, ['sepal_length', 'petal_length']])

Kiểm tra lại dòng 10 đến 14 sau khi điền 1.0:
    sepal_length  petal_length
10           5.4           1.0
11           4.8           1.0
12           4.8           1.0
13           4.3           1.0
14           5.8           1.0

### Step 8. Xóa cột 'class' khỏi DataFrame

In [7]:
del iris['class']
# Hoặc: iris.drop(columns=['class'], inplace=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### Step 9. Gán 3 dòng đầu tiên của DataFrame thành NaN

In [8]:
iris.iloc[0:3, :] = np.nan
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### Step 10. Xóa tất cả các dòng có chứa giá trị NaN

In [9]:
iris.dropna(axis=0, inplace=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4
6           4.6          3.4           1.4          0.3
7           5.0          3.4           1.5          0.2

### Step 11. Đặt lại chỉ số (Reset Index) để chỉ số bắt đầu lại từ 0
*Sử dụng reset_index(drop=True, inplace=True).*

In [10]:
iris.reset_index(drop=True, inplace=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.6          3.1           1.5          0.2
1           5.0          3.6           1.4          0.2
2           5.4          3.9           1.7          0.4
3           4.6          3.4           1.4          0.3
4           5.0          3.4           1.5          0.2

### BONUS: Kiểm tra kích thước cuối cùng và các thống kê mô tả sau khi làm sạch

In [11]:
print('Kích thước DataFrame cuối cùng:', iris.shape)
print('\nThống kê mô tả dữ liệu:')
print(iris.describe())

Kích thước DataFrame cuối cùng: (147, 4)

Thống kê mô tả dữ liệu:
       sepal_length  sepal_width  petal_length  petal_width
count    147.000000   147.000000    147.000000   147.000000
mean       5.862585     3.050340      3.741497     1.219048
std        0.824971     0.436263      1.840520     0.757278
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.500000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000