# Bài 00: Tạo Series và DataFrame - Bài tập Pokemon
### Giới thiệu:
Trong bài tập này, bạn sẽ tự tay tạo một DataFrame từ dữ liệu dạng Python Dictionary, thay đổi thứ tự các cột, bổ sung cột mới và kiểm tra kiểu dữ liệu của các cột.

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2. Tạo một data dictionary chứa thông tin Pokemon

In [2]:
raw_data = {
    'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
    'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
    'type': ['grass', 'fire', 'water', 'bug'],
    'hp': [45, 39, 44, 45],
    'pokedex': ['yes', 'no', 'yes', 'no']
}
raw_data

{'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
 'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
 'type': ['grass', 'fire', 'water', 'bug'],
 'hp': [45, 39, 44, 45],
 'pokedex': ['yes', 'no', 'yes', 'no']}

### Step 3. Gán dictionary vào một biến có tên gọi là pokemon (tạo DataFrame)

In [3]:
pokemon = pd.DataFrame(raw_data)
pokemon

         name   evolution   type  hp pokedex
0   Bulbasaur     Ivysaur  grass  45     yes
1  Charmander  Charmeleon   fire  39      no
2    Squirtle   Wartortle  water  44     yes
3    Caterpie     Metapod    bug  45      no

### Step 4. Sắp xếp lại thứ tự các cột thành: name, type, hp, evolution, pokedex

In [4]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Thêm một cột mới có tên là place và điền các địa danh tùy ý

In [5]:
pokemon['place'] = ['park', 'mountain', 'lake', 'forest']
pokemon

         name   type  hp   evolution pokedex     place
0   Bulbasaur  grass  45     Ivysaur     yes      park
1  Charmander   fire  39  Charmeleon      no  mountain
2    Squirtle  water  44   Wartortle     yes      lake
3    Caterpie    bug  45     Metapod      no    forest

### Step 6. Hiển thị kiểu dữ liệu của từng cột

In [6]:
pokemon.dtypes

name           str
type           str
hp           int64
evolution      str
pokedex        str
place          str
dtype: object

### BONUS: Câu hỏi tự tạo - Tìm Pokemon có HP cao nhất và lọc các Pokemon hệ cỏ (grass)

In [7]:
# 1. Tìm Pokemon có lượng HP cao nhất
max_hp_pokemon = pokemon[pokemon['hp'] == pokemon['hp'].max()]
print('Pokemon co HP cao nhat:')
print(max_hp_pokemon)

# 2. Loc Pokemon co he la grass
grass_pokemon = pokemon[pokemon['type'] == 'grass']
print('\nPokemon he Grass:')
print(grass_pokemon)

Pokemon co HP cao nhat:
        name   type  hp evolution pokedex   place
0  Bulbasaur  grass  45   Ivysaur     yes    park
3   Caterpie    bug  45   Metapod      no  forest

Pokemon he Grass:
        name   type  hp evolution pokedex place
0  Bulbasaur  grass  45   Ivysaur     yes  park