# Bài 03: Thống Kê Dữ Liệu (US Baby Names)
### Giới thiệu:
Trong bài tập này, chúng ta sử dụng tập dữ liệu tên trẻ em sinh tại Mỹ (giai đoạn 2004 - 2014) từ Kaggle để thực hành:
- Xóa bỏ các cột thừa (cột index phụ, cột ID vô nghĩa) bằng .drop().
- Đếm phân phối tần suất của biến phân loại (Categorical data) bằng .value_counts().
- Gom nhóm dữ liệu theo tên và tính toán các đại lượng thống kê mô tả: Mean (trung bình), Median (trung vị), Std (độ lệch chuẩn), Min, Max, Quartiles (các phân vị 25%, 50%, 75%).
- Tìm kiếm giá trị cực đại và cực tiểu bằng .idxmax() và mặt nạ Boolean.

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2 & 3. Đọc dữ liệu từ URL và gán vào biến baby_names

In [2]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv'
baby_names = pd.read_csv(url)
baby_names.head()

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

### Step 4. Xem 10 dòng đầu tiên của tập dữ liệu

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Xóa bỏ hai cột thừa: 'Unnamed: 0' và 'Id'
*Sử dụng drop(columns=...) với axis=1 để loại bỏ cột.*

In [4]:
cols_to_drop = [c for c in ['Unnamed: 0', 'Id'] if c in baby_names.columns]
baby_names.drop(columns=cols_to_drop, inplace=True)
baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. Trong tập dữ liệu, số lượng tên cho Bé gái (F) hay Bé trai (M) nhiều hơn?

In [5]:
gender_counts = baby_names['Gender'].value_counts()
print(gender_counts)
if gender_counts['F'] > gender_counts['M']:
    print('=> Số lượng tên Bé gái (F) nhiều hơn.')
else:
    print('=> Số lượng tên Bé trai (M) nhiều hơn.')

Gender
F    558846
M    457549
Name: count, dtype: int64
=> Số lượng tên Bé gái (F) nhiều hơn.

### Step 7. Nhóm tập dữ liệu theo tên (Name) và tính tổng số lượng sinh (Count), gán vào biến names

In [6]:
names = baby_names.groupby('Name')['Count'].sum().reset_index()
names.head()

      Name  Count
0    Aaban     12
1    Aadan     23
2  Aadarsh      5
3    Aaden   3426
4   Aadhav      6

### Step 8. Có bao nhiêu tên khác nhau tồn tại trong tập dữ liệu?

In [7]:
num_unique_names = len(names)
print('Số lượng tên khác nhau trong tập dữ liệu:', num_unique_names)

Số lượng tên khác nhau trong tập dữ liệu: 17632

### Step 9. Tên nào xuất hiện nhiều nhất (được đặt nhiều nhất)?

In [8]:
idx_max = names['Count'].idxmax()
most_popular_name = names.loc[idx_max]
print('Tên xuất hiện nhiều nhất:')
print(most_popular_name)

Tên xuất hiện nhiều nhất:
Name      Jacob
Count    242874
Name: 7198, dtype: object

### Step 10. Có bao nhiêu tên khác nhau có số lần xuất hiện ít nhất?

In [9]:
min_count = names['Count'].min()
num_least_popular = (names['Count'] == min_count).sum()
print(f'Số lần xuất hiện ít nhất là {min_count}, và có {num_least_popular} tên có số lần xuất hiện này.')

Số lần xuất hiện ít nhất là 5, và có 2578 tên có số lần xuất hiện này.

### Step 11. Giá trị trung vị (median) của số lần xuất hiện tên là bao nhiêu?

In [10]:
median_count = names['Count'].median()
print('Trung vị (Median) số lần xuất hiện:', median_count)

Trung vị (Median) số lần xuất hiện: 49.0

### Step 12. Độ lệch chuẩn (standard deviation) của số lần xuất hiện tên là bao nhiêu?

In [11]:
std_count = names['Count'].std()
print(f'Độ lệch chuẩn (Std): {std_count:.2f}')

Độ lệch chuẩn (Std): 11006.07

### Step 13. Lấy bảng tổng kết thống kê mô tả: Mean, Min, Max, Std và các tứ phân vị (Quartiles)

In [12]:
names['Count'].describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64