# Bài 05: Áp Dụng Hàm Số Trong Pandas - Apply (Học Sinh & Tiêu Thụ Cồn)
### Giới thiệu:
Thư viện Pandas cung cấp phương thức .apply() cực kỳ mạnh mẽ để áp dụng bất kỳ hàm tự tạo nào (Custom Function hoặc Lambda Function) lên từng hàng, từng cột hoặc từng phần tử của bảng dữ liệu:
- Cắt lát bảng dữ liệu theo nhãn cột bằng .loc[:, 'start':'end'].
- Viết và sử dụng hàm ẩn danh lambda.
- Hiểu tính bất biến (Immutability) khi sử dụng .apply() và cách gán đè để cập nhật dữ liệu.
- Viết hàm logic phân nhánh với if...else và tạo ra đặc trưng cột mới.
- Áp dụng hàm biến đổi trên toàn bộ bảng dữ liệu (df.map() / df.applymap()).

### Step 1. Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

### Step 2 & 3. Đọc dữ liệu từ URL và gán vào biến df

In [2]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv'
df = pd.read_csv(url)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 4. Cắt lát DataFrame từ cột 'school' cho đến cột 'guardian'
*Sử dụng .loc[:, 'school':'guardian'] để lấy toàn bộ các hàng và dải cột từ school đến guardian.*

In [3]:
df = df.loc[:, 'school':'guardian']
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Tạo một lambda function viết hoa chữ cái đầu của chuỗi (capitalize)

In [4]:
capitalize_func = lambda x: x.capitalize() if isinstance(x, str) else x

### Step 6. Áp dụng hàm viết hoa cho cả hai cột Mjob (nghề của mẹ) và Fjob (nghề của bố)

In [5]:
df['Mjob'].apply(capitalize_func)
df['Fjob'].apply(capitalize_func)

0       Teacher
1         Other
2         Other
3      Services
4         Other
         ...
390    Services
391    Services
392       Other
393       Other
394     At_home
Name: Fjob, Length: 395, dtype: str

### Step 7. In ra các dòng cuối cùng của tập dữ liệu

In [6]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 8. Tại sao DataFrame gốc vẫn là chữ thường? Khắc phục điều này!
**Giải thích:** Phương thức .apply() trả về một Series mới chứa kết quả biến đổi chứ KHÔNG trực tiếp thay đổi DataFrame gốc (không có cơ chế inplace).  
**Cách khắc phục:** Ta phải gán ngược kết quả trả về vào chính các cột đó: df['col'] = df['col'].apply(...).

In [7]:
df['Mjob'] = df['Mjob'].apply(capitalize_func)
df['Fjob'] = df['Fjob'].apply(capitalize_func)
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 9. Tạo hàm tên là majority trả về kiểu boolean cho cột mới 'legal_drinker' (Tuổi > 17 được coi là đủ tuổi uống đồ có cồn)

In [8]:
def majority(age):
    return age > 17

df['legal_drinker'] = df['age'].apply(majority)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father,False

### Step 10. Nhân tất cả các giá trị số trong tập dữ liệu với 10 (giữ nguyên chuỗi)
*Sử dụng .map() (hoặc .applymap() trong pandas cũ) để biến đổi từng ô dữ liệu.*

In [9]:
def multiply_10(val):
    if isinstance(val, (int, float, np.number)) and not isinstance(val, bool):
        return val * 10
    return val

# Áp dụng hàm lên từng ô của DataFrame
if hasattr(df, 'map'):
    df_multiplied = df.map(multiply_10)
else:
    df_multiplied = df.applymap(multiply_10)

df_multiplied.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,mother,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,course,father,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,other,mother,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,home,mother,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,home,father,False